  
language: node_js

node_js: 
 - "10.15.1"

# Travis-CI Caching
cache:
  directories:
    - node_modules
env:
  - CI=true

install:
  - npm install

script:
  - npm run build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GitHub_TOKEN
  local_dir: storybook-static
  on:
    branch: master